version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Newtonsoft.Json
    versions:
    - 13.0.1
  - dependency-name: Microsoft.Toolkit.Uwp.Notifications
    versions:
    - 7.0.0
    - 7.0.1
  - dependency-name: Microsoft.CodeAnalysis.CSharp
    versions:
    - 3.9.0
