version: 1.0.{build}
skip_non_tags: true
image: Visual Studio 2019
configuration: Release
init:
- ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME)"
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(APPVEYOR_REPO_TAG_NAME)
  assembly_file_version: $(APPVEYOR_REPO_TAG_NAME)
  assembly_informational_version: $(APPVEYOR_REPO_TAG_NAME)
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(APPVEYOR_REPO_TAG_NAME)
  package_version: $(APPVEYOR_REPO_TAG_NAME)
  assembly_version: $(APPVEYOR_REPO_TAG_NAME)
  file_version: $(APPVEYOR_REPO_TAG_NAME)
  informational_version: $(APPVEYOR_REPO_TAG_NAME)
build_script:
- ps: >-
    dotnet publish BuildNotifications\BuildNotifications.csproj -c Release -r win-x64

    & dotnet publish BuildNotifications.Core\BuildNotifications.Core.csproj -c Release -r win-x64

    & dotnet publish Plugins\BuildNotifications.Plugin.Tfs\BuildNotifications.Plugin.Tfs.csproj -c Release -r win-x64

    & nuget restore ToastNotificationsPlugin\ToastNotificationsPlugin.csproj

    & msbuild ToastNotificationsPlugin\ToastNotificationsPlugin.csproj /t:Build /p:Configuration=Release

    & Scripts/create-release-package.ps1
test: off
artifacts:
- path: Releases/RELEASES
  name: ReleasesFile
- path: Releases/Setup.exe
  name: SetupExe
- path: Releases/*-full.nupkg
  name: FullNupkg
- path: Releases/*-delta.nupkg
  name: DeltaNupkg
deploy:
- provider: GitHub
  auth_token:
    secure: TCujf+T4HHnH1w6WCybblkHMILi6HYQaZTYyLPG56w1mruNZ3aaBKtEoC+ubuVEI
  artifact: ReleasesFile,SetupExe,FullNupkg,DeltaNupkg
  draft: true
  prerelease: true