version: 1.0.{build}
image: Visual Studio 2019 Preview
configuration: Release
init:
- ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH)-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
before_build:
- ps: nuget restore
build:
  parallel: true
  verbosity: normal