version: 0.1.{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
init:
- ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH)-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"

    & Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"

    & $env:temp\dotnet-install.ps1 -Architecture x64 -Version '3.0.100-preview9-014004' -InstallDir "$env:ProgramFiles\dotnet"
before_build:
- ps: nuget restore
build:
  parallel: true
  verbosity: normal