name: CI Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup Java for CodeCoverage results
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
        
    - name: Install .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[16.8,)'
      
    - name: Download Coverage reporter
      run: Invoke-WebRequest -Uri 'https://github.com/codacy/codacy-coverage-reporter/releases/download/11.2.2/codacy-coverage-reporter-assembly-11.2.2.jar' -UseBasicParsing -OutFile  ./codacy-test-reporter.jar

    - name: nuget restore
      run: nuget restore
      
    - name: Build 
      run: msbuild -m BuildNotifications.sln /t:Build /p:Configuration=Release
    
    - name: Run tests
      run: dotnet test BuildNotifications.sln --no-build --configuration Release -r CoverageResults --collect:"XPlat Code Coverage"
    
    - name: Upload code coverage results
      run: java -jar ./codacy-test-reporter.jar report -l CSharp -r ./CoverageResult/**/coverage.cobertura.xml -t ${{ secrets.CODACY_PROJECT_TOKEN }} --partial
      if: github.head_ref == 0

    - name: Complate upload of code coverage results
      run: java -jar ./codacy-test-reporter.jar final -t ${{ secrets.CODACY_PROJECT_TOKEN }}
      if: github.head_ref == 0
