name: CI Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
        
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Install coverage tools
      run: dotnet tool install --global coverlet.console
      
    - name: Add coverage tool to core test project
      run: dotnet add BuildNotifications.Core.Tests/BuildNotifications.Core.Tests.csproj package coverlet.msbuild
      
    - name: Add coverage tool to test project
      run: dotnet add BuildNotifications.Tests/BuildNotifications.Tests.csproj package coverlet.msbuild
      
    - name: nuget restore
      run: nuget restore
      
    - name: Build 
      run: msbuild BuildNotifications.sln /t:Build /p:Configuration=Release
    
    - name: Run tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=coverage /p:Exclude=[xunit.*]* BuildNotifications.sln --no-build --configuration Release

    - name: Upload code coverage results
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ./BuildNotifications.Core.Tests/coverage.cobertura.xml, ./BuildNotifications.Tests/coverage.cobertura.xml
      if: github.head_ref == 0
